name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*.*'  # Trigger on version tags (e.g., v1.0.0.0)

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: '3.1.1'

      - name: Build executable
        run: stack build --copy-bins
        env:
          STACK_ROOT: ${{ runner.temp }}/stack-root
          HOME: ${{ runner.temp }}

      - name: Run tests
        run: stack test
        env:
          STACK_ROOT: ${{ runner.temp }}/stack-root
          HOME: ${{ runner.temp }}

      - name: Package executable
        run: |
          mkdir -p dist
          cp $(stack path --local-install-root)/bin/chunktool* dist/
        env:
          STACK_ROOT: ${{ runner.temp }}/stack-root
          HOME: ${{ runner.temp }}
    
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chunktool-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: chunktool-${{ matrix.os }}

      - name: List files in dist
        run: ls -l dist

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
