name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*.*'  # Trigger on version tags (e.g., v1.0.0.0)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Haskell stack
        uses: actions/setup-haskell@v1
        with:
          stack-version: '3.1.1'

      - name: Install dependencies
        run: stack setup

      - name: Build executable
        run: stack build --copy-bins
        env:
          STACK_ROOT: ${{ runner.temp }}/stack-root
          HOME: ${{ runner.temp }}

      - name: Run tests
        run: stack test
        env:
          STACK_ROOT: ${{ runner.temp }}/stack-root
          HOME: ${{ runner.temp }}

      - name: Package executable
        run: |
          mkdir -p dist
          cp $(stack path --local-install-root)/bin/chunktool* dist/
        env:
          STACK_ROOT: ${{ runner.temp }}/stack-root
          HOME: ${{ runner.temp }}
    
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chunktool-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: chunktool-ubuntu-latest

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

